#local用
version: '3'

services:
  mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: english_frequency
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  api:
    build:
      context: .
    ports:
      - "1323:1323"
    environment:
      - ENV=local
